# Site settings
title: Wenxiang's Main Page
email: wenxiang.weng@gmail.com
description: > # Welcome to my main page.
  Welcome to my main page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wenxiangweng.github.io" # the base hostname & protocol for your site
twitter_username: wenxiangweng
github_username:  wenxiangweng

# Build settings
markdown: kramdown
